steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/doit-public/doit-easily/deployer:$TAG_NAME', '-f', 'deployer', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/doit-public/doit-easily/deployer:$TAG_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/doit-public/doit-easily/tester:$TAG_NAME', '-f', 'apptest/tester/', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/doit-public/doit-easily/tester:$TAG_NAME']
#  todo can we run verifier? it requires a cluster...