x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: 'v0.0.1-alpha7'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    '': # primary image
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
properties:
  app_instance_name:
    type: string
    default: entitlement
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  is_codelab:
    type: boolean
    default: false
  marketplace_project:
    type: string
  backend_project:
    type: string
  log_level:
    type: string
    default: info
  slack_webhook:
    type: string
  event_topic:
    type: string
  subscription_id:
    type: string
  deployment_service_account:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: The kubernetes service account that will run the deployments. Bound to "google_service_account_email" via Workload Identity
  google_service_account_email:
    type: string
    description: The google service account with permissions to access the procurement API. Bound to "deployment_service_account" via Workload Identity
required:
- app_instance_name
- namespace
- is_codelab
- marketplace_project
- backend_project
- log_level
- slack_webhook
- event_topic
- subscription_id
- deployment_service_account
- google_service_account_email